name: Request Assignment Repository
description: Instantly provision your private assignment repository using the course code.
title: "Private Repository Request"
labels: ["provision-repo"]
body:
  - type: markdown
    attributes:
      value: |
        ### Welcome to Project and Portfolio: Development IV (aka DEV4)!
        Clicking submit below will generate your personal, private workspace under our organization.
  - type: input
    id: passcode
    attributes:
      label: Course Code
      placeholder: Enter the course code provided by your instructor.
    validations:
      required: true
